accent = "#9099a5"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#0A101F"
selection_foreground = "#ffffff"
selection_background = "#9099a5"

color0 = "#0A101F"
color1 = "#811139"
color2 = "#5C637A"
color3 = "#e5af1b"
color4 = "#9099a5"
color5 = "#e2687c"
color6 = "#C24F40"
color7 = "#F5ECDF"
color8 = "#6B72A8"
color9 = "#e21d63"
color10 = "#5C637A"
color11 = "#f0d17c"
color12 = "#9099a5"
color13 = "#e88595"
color14 = "#DC9B68"
color15 = "#C7D3E0"
