
# ========= Border =========
file_panel_border = '#F5ECDF'
sidebar_border = '#F5ECDF'
footer_border = '#F5ECDF'

# ========= Border Active =========
file_panel_border_active = '#9099a5'
sidebar_border_active = '#9099a5'
footer_border_active = '#9099a5'
modal_border_active = '#9099a5'

# ========= Background (bg) =========
full_screen_bg = '#0A101F'
file_panel_bg = '#0A101F'
sidebar_bg = '#0A101F'
footer_bg = '#0A101F'
modal_bg = '#0A101F'

# ========= Foreground (fg) =========
full_screen_fg = '#ffffff'
file_panel_fg = '#ffffff'
sidebar_fg = '#ffffff'
footer_fg = '#ffffff'
modal_fg = '#ffffff'

# ========= Special Color =========
cursor = '#ffffff'
correct = '#5C637A'
error = '#811139'
hint = '#C24F40'
cancel = '#811139'
gradient_color = ['#0A101F', "#6B72A8"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#0A101F'
file_panel_top_path = '#6B72A8'
file_panel_item_selected_fg = '#6B72A8'
file_panel_item_selected_bg = '#0A101F'

# ========= Sidebar Special Items =========
sidebar_title = '#C7D3E0'
sidebar_item_selected_fg = '#6B72A8'
sidebar_item_selected_bg = '#0A101F'
sidebar_divider = '#F5ECDF'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#811139'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#5C637A'
